export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SIGN_UP = 'AUTH_SIGN_UP';
export const AFTER_SIGN_UP = "AFTER_SIGN_UP";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED";
export const START="START";
export const CHANGE_SOUNDS="CHANGE_SOUNDS";


export const GET_MY_TEAMS_SUCCESS = "GET_MY_TEAMS_SUCCESS";
export const GET_MY_TEAMS_FAILED = "GET_MY_TEAMS_FAILED";
export const START_CREATE_TEAM = "START_CREATE_TEAM";
export const SUCCESS_CREATE_TEAM = "SUCCESS_CREATE_TEAM";
export const FAILED_CREATE_TEAM = "FAILED_CREATE_TEAM";
export const END_CREATE_TEAM = "END_CREATE_TEAM";
export const TEAM_SELECTED_SUCCESS = "TEAM_SELECTED_SUCCESS";
export const TEAM_SELECTED_FAILED = "TEAM_SELECTED_FAILED";
export const TEAM_SELECTED_START = "TEAM_SELECTED_START";
export const CHANGE_MY_STATE = "CHANGE_MY_STATE";
export const RECEIVE_CHANGE_STATE = "RECEIVE_CHANGE_STATE";


export const OPENED_CHAT = "OPEN_CHAT";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const CHECK_UNREAD_MESSAGE = "CHECK_UNREAD_MESSAGE";
export const SET_SEEN_USER_MESSAGE = "SET_SEEN_USER_MESSAGE";
export const CHECK_UNREAD_TEAM_MESSAGE = "CHECK_UNREAD_TEAM_MESSAGE";
export const SET_SEEN_TEAM_MESSAGE = "SET_SEEN_TEAM_MESSAGE";
export const LOAD_MORE_MESS_USER_SUCCESS = "LOAD_MORE_MESS_USER_SUCCESS";
export const LOAD_MORE_MESS_USER_FAILED = "LOAD_MORE_MESS_USER_FAILED";
export const LOAD_MORE_MESS_USER_START = "LOAD_MORE_MESS_USER_START";
export const CHANGE_SEEN_USER_MESS = "CHANGE_SEEN_USER_MESS";


export const SET_POMODORO_SESSION = "SET_POMODORO_SESSION";
export const SET_POMODORO_DURATION = "SET_POMODORO_DURATION";
export const RESET_POMODORO = "RESET_POMODORO";

