export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SIGN_UP='AUTH_SIGN_UP';
export const AFTER_SIGN_UP="AFTER_SIGN_UP";

export const GET_MY_TEAMS_SUCCESS="GET_MY_TEAMS_SUCCESS";
export const GET_MY_TEAMS_FAILED="GET_MY_TEAMS_FAILED";
export const START_CREATE_TEAM="START_CREATE_TEAM";
export const SUCCESS_CREATE_TEAM="SUCCESS_CREATE_TEAM";
export const FAILED_CREATE_TEAM="FAILED_CREATE_TEAM";
export const END_CREATE_TEAM="END_CREATE_TEAM";
export const TEAM_SELECTED_SUCCESS="TEAM_SELECTED_SUCCESS";
export const TEAM_SELECTED_FAILED="TEAM_SELECTED_FAILED";
export const TEAM_SELECTED_START="TEAM_SELECTED_START";



